apiVersion: v1
items:  
  - apiVersion: v1
    kind: Service
    metadata:
      name: reviews-api
    spec:
      type: ClusterIP
      selector:
        app: reviews-api
      ports:
        - protocol: TCP
          port: 80
          targetPort: 5052
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: reviews-api
    spec:
      selector:
        matchLabels:
          app: reviews-api
      replicas: 1
      template:
        metadata:
          labels:
            app: reviews-api
        spec:
          containers:
            - name: reviews-api
              image: "reviews"
              imagePullPolicy: Never
              env:
              - name: MONGODB_HOST
                valueFrom:
                   configMapKeyRef:
                    name: mongodb-config
                    key: host
              - name: MONGODB_PORT
                valueFrom:
                   configMapKeyRef:
                    name: mongodb-config
                    key: port
              - name: MONGODB_USER
                valueFrom:
                   secretKeyRef:
                    name: mongodb-secret
                    key: username
              - name: MONGODB_AUTH_MECHANISM
                valueFrom:
                   configMapKeyRef:
                    name: mongodb-config
                    key: auth_mechanism
              - name: MONGODB_PASSWORD
                valueFrom:
                   secretKeyRef:
                    name: mongodb-secret
                    key: password
              - name: MONGODB_DATABASE
                value: "reviews"              
              volumeMounts:
              - name: varlog
                mountPath: /var/log
          terminationGracePeriodSeconds: 30
          volumes:
          - name: varlog
            hostPath:
              path: /var/log         
          
kind: List
metadata: {}